name: mordor tests

on:
  push:
    branches: [ develop, release-0.0.1 ]
  pull_request:
    branches: [ develop ]

jobs:
  mnist-trainer:
    runs-on: [ mordor ]

    strategy:
      matrix:
        ginter: [ 1, 2 ]
        memopt: [ '--cpu-offload', '' ] 
    steps:
    - uses: actions/checkout@v3
    - name: install AxoNN
      run: |
        pip install -e .
        pip install -r requirements.txt
    - name: Train MNIST
      run: |
        pwd
        G_inter=${{ matrix.ginter }}
        echo "training with G_inter = ${G_inter}, G_data = $(( 2 / G_inter  )) ${{ matrix.memopt }}" 
    - name: uninstall AxoNN
        pip uninstall axonn
